name: appengine-analytics
on:
  push:
    branches:
    - main
jobs:
  test:
    steps:
    - uses: google-github-actions/auth@v0.7.1
      with:
        workload_identity_provider: 'projects/1046198160504/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'kokoro-system-test@long-door-651.iam.gserviceaccount.com'
        create_credentials_file: 'true'
        access_token_lifetime: 600s
